print('olá, mundo')
print('Esta é uma frase qualquer')
print('O dia está ensolarado')
print('Perfeito para tomar um sorvetinho')
print('Enquanto assisto um filminho ')
print('mais tarde vou no shopphing')
print('Comer um mc')
print('Ir pra casa e dormir')
print('Porque no outro dia vou trabalhar')
print('Depois ficar de bobeira')